name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'IaC/terraform-deployment/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'IaC/terraform-deployment/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  TF_VERSION: '1.9.8'
  WORKING_DIR: './IaC/terraform-deployment'

jobs:
  terraform-check:
    name: 'Terraform Check'
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    outputs:
      environment: ${{ steps.determine-env.outputs.environment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine Environment
      id: determine-env
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "environment=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "environment=prod" >> $GITHUB_OUTPUT
        else
          echo "environment=dev" >> $GITHUB_OUTPUT
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Format
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform fmt -check -recursive

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform init -backend=false

    - name: Terraform Validate
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform validate

  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_MSI_CLIENTID }}
          tenant-id: ${{ secrets.AZURE_MSI_TENANTID }}
          subscription-id: ${{ secrets.AZURE_MSI_SUBSCRIPTIONID }}
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: terraform-check
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
    environment: ${{ needs.terraform-check.outputs.environment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_MSI_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_MSI_TENANTID }}
        subscription-id: ${{ secrets.AZURE_MSI_SUBSCRIPTIONID }}
        auth-type: IDENTITY

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ needs.terraform-check.outputs.environment }}.terraform.tfstate"

    - name: Terraform Plan
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        terraform plan \
          -var-file="environments/${{ needs.terraform-check.outputs.environment }}.tfvars" \
          -var="user_object_id=${{ secrets.USER_OBJECT_ID }}" \
          -out="${{ needs.terraform-check.outputs.environment }}.tfplan"

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-${{ needs.terraform-check.outputs.environment }}
        path: ${{ env.WORKING_DIR }}/${{ needs.terraform-check.outputs.environment }}.tfplan
        retention-days: 5

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: [terraform-check, terraform-plan]
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
    environment: ${{ needs.terraform-check.outputs.environment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_MSI_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_MSI_TENANTID }}
        subscription-id: ${{ secrets.AZURE_MSI_SUBSCRIPTIONID }}
        auth-type: IDENTITY

    - name: Download Plan Artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan-${{ needs.terraform-check.outputs.environment }}
        path: ${{ env.WORKING_DIR }}

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ needs.terraform-check.outputs.environment }}.terraform.tfstate"

    - name: Terraform Apply
      working-directory: ${{ env.WORKING_DIR }}
      run: terraform apply -auto-approve "${{ needs.terraform-check.outputs.environment }}.tfplan"

  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    needs: terraform-check
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
    environment: ${{ needs.terraform-check.outputs.environment }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_MSI_CLIENTID }}
        tenant-id: ${{ secrets.AZURE_MSI_TENANTID }}
        subscription-id: ${{ secrets.AZURE_MSI_SUBSCRIPTIONID }}
        auth-type: IDENTITY

    - name: Terraform Init
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP }}" \
          -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}" \
          -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER }}" \
          -backend-config="key=${{ needs.terraform-check.outputs.environment }}.terraform.tfstate"

    - name: Terraform Destroy
      working-directory: ${{ env.WORKING_DIR }}
      run: |
        terraform destroy -auto-approve \
          -var-file="environments/${{ needs.terraform-check.outputs.environment }}.tfvars" \
          -var="user_object_id=${{ secrets.USER_OBJECT_ID }}"
